# Generated by Django 6.0.4 on 2026-04-13 17:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('Admin', 'Administrador'), ('Director', 'Director'), ('Optico', 'Óptico'), ('Comercial', 'Comercial'), ('Cliente', 'Cliente')], default='Optico', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo_cita', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('optico', models.ForeignKey(limit_choices_to={'rol': 'Optico'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('ant_medicos', models.TextField(blank=True)),
                ('ant_oculares', models.TextField(blank=True)),
                ('pantallas', models.CharField(max_length=100)),
                ('gafas_sol', models.BooleanField(default=False)),
                ('lentillas', models.BooleanField(default=False)),
                ('recomendaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('optico', models.ForeignKey(limit_choices_to={'rol': 'Optico'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graduacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_esfera', models.DecimalField(decimal_places=2, max_digits=5)),
                ('od_cilindro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('od_eje', models.IntegerField()),
                ('od_adicion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('od_agudeza', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oi_esfera', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oi_cilindro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oi_eje', models.IntegerField()),
                ('oi_adicion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oi_agudeza', models.DecimalField(decimal_places=2, max_digits=5)),
                ('queratometria', models.TextField(blank=True)),
                ('biomicroscopio', models.TextField(blank=True)),
                ('tanometria', models.TextField(blank=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Montura', 'Montura'), ('Lente', 'Lente'), ('Accesorio', 'Accesorio'), ('Contactología', 'Contactología')], max_length=50)),
                ('subcategoria', models.CharField(help_text='Ej: Monofocal, Hidrogel, Pasta...', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
                ('comercial', models.ForeignKey(limit_choices_to={'rol': 'Comercial'}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_vendidos', to=settings.AUTH_USER_MODEL)),
                ('optico', models.ForeignKey(limit_choices_to={'rol': 'Optico'}, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_validados', to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(to='gestion.producto')),
            ],
        ),
    ]
