# Generated by Django 6.0.4 on 2026-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='tipo_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
