# Generated by Django 6.0.4 on 2026-04-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_pedido_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='TEMP', max_length=20, unique=True, verbose_name='Código/SKU'),
            preserve_default=False,
        ),
    ]
