# Generated by Django 6.0.4 on 2026-04-13 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_consulta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacion',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduacion', to='gestion.consulta'),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='od_adicion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='od_agudeza',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='od_cilindro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='od_eje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='od_esfera',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='oi_adicion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='oi_agudeza',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='oi_cilindro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='oi_eje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='oi_esfera',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='queratometria',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='tanometria',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
