# Generated by Django 6.0.4 on 2026-04-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_pedido_comercial_alter_pedido_optico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduacion',
            name='queratometria',
        ),
        migrations.RemoveField(
            model_name='graduacion',
            name='tanometria',
        ),
        migrations.AddField(
            model_name='graduacion',
            name='od_queratometria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Queratometría OD'),
        ),
        migrations.AddField(
            model_name='graduacion',
            name='od_tonometria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tonometría OD'),
        ),
        migrations.AddField(
            model_name='graduacion',
            name='oi_queratometria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Queratometría OI'),
        ),
        migrations.AddField(
            model_name='graduacion',
            name='oi_tonometria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tonometría OI'),
        ),
    ]
