# Generated by Django 6.0.4 on 2026-04-14 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_graduacion_queratometria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encargo', models.DateTimeField(auto_now_add=True)),
                ('montura_marca_modelo', models.CharField(blank=True, max_length=200, verbose_name='Montura')),
                ('montura_en_stock', models.BooleanField(default=True, verbose_name='¿En stock?')),
                ('proveedor_lentes', models.CharField(max_length=100)),
                ('material', models.CharField(choices=[('ORG', 'Orgánico'), ('MIN', 'Mineral')], default='ORG', max_length=3)),
                ('od_tipo', models.CharField(blank=True, choices=[('LEJ', 'Lejos'), ('CER', 'Cerca'), ('PRO', 'Progresivo'), ('OCU', 'Ocupacional')], max_length=3, null=True)),
                ('od_indice', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Índice OD')),
                ('od_codigo', models.CharField(blank=True, max_length=50)),
                ('od_nombre', models.CharField(blank=True, max_length=200)),
                ('od_precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('oi_tipo', models.CharField(blank=True, choices=[('LEJ', 'Lejos'), ('CER', 'Cerca'), ('PRO', 'Progresivo'), ('OCU', 'Ocupacional')], max_length=3, null=True)),
                ('oi_indice', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Índice OI')),
                ('oi_codigo', models.CharField(blank=True, max_length=50)),
                ('oi_nombre', models.CharField(blank=True, max_length=200)),
                ('oi_precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('TAL', 'En Taller'), ('LIS', 'Listo'), ('ENT', 'Entregado')], default='PEN', max_length=3)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos', to='gestion.cliente')),
                ('graduacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.graduacion', verbose_name='Graduación vinculada')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_encargos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
