# Generated by Django 6.0.4 on 2026-04-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_encargo_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='encargo',
            name='montura_precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='encargo',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='¿Está pagado?'),
        ),
        migrations.AddField(
            model_name='encargo',
            name='total_encargo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente (Taller)'), ('LIS', 'Listo para entrega'), ('TAL', 'En taller'), ('ENT', 'Entregado a cliente')], default='PEN', max_length=3),
        ),
    ]
