# Generated by Django 6.0.4 on 2026-04-15 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_encargo_metodo_pago_encargo_montura_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_rapidas', to='gestion.cliente'),
        ),
    ]
